spring:
  application:
    name: product-service
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/rest-api
server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

management:
  tracing:
    sampling:
      probability: 1.0