spring:
  cloud:
    bus:
      refresh:
        enabled: true
      env:
        enabled: true
  application:
    name: config-client
  config:
    import: "optional:configserver:http://localhost:8888"
  kafka:
    bootstrap-servers: http://localhost:9092
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

