scrape_configs:
  - job_name: 'MyAppMetrics_8080'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          application: 'Product Service'

  - job_name: 'MyAppMetrics_7070'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'host.docker.internal:7070' ]
        labels:
          application: 'Inventory Service'